model:
  name: mul_resnet18
  path: checkpoints
  load_from_checkpoint: True
  checkpoint_name: checkpoint_latest.pth
  use_gpu: True
  pretrained: True
  feat:
    backbone: resnet18
    freq_branch_enabled: True
    freq_filter: [0.2, 0.4, 0.6, 0.8]    # use all thresholds and stack the frequency map
    noise_branch_enabled: True
    fusion_out_channels : 1536
  head_cls: 2

test:
  dataset:
    data_root: '/home/sxf/data/synthesized_binary_dataset'
    batch_size: 1
  data_transforms:
    crop: 224
    crop_enabled: True
    flip_enabled: True
    normalize:
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]
    normalize_enabled: True
    post_processing:
      gaussian:
        prob: 0.5
        sigma: 0.1
      gaussian_enabled: True
      jpeg:
        prob: 0.5
        quality: [90, 95]    # random choose a quality
      jpeg_enabled: True
    post_processing_enabled: True
    resize: 256
    resize_enabled: True
  metrics: [ACC, AUC, F1, mAP]
  save_dir: output
  seed: 1
